export const TENANT_OVERVIEW_MOVE_PAGE = `TENANT_OVERVIEW_MOVE_PAGE`
export const TENANT_SET_TENANT_LIST = 'TENANT_SET_TENANT_LIST'
export const TENANT_OVERVIEW_PAGE_REQUEST = 'TENANT_OVERVIEW_PAGE_REQUEST'
export const TENANT_SET_TENANT_OVERVIEW = 'TENANT_SET_TENANT_OVERVIEW'
export const TENANT_SET_TENANT_PLAN = 'TENANT_SET_TENANT_PLAN'
export const TENANT_GET_TENANT_LIST = 'TENANT_GET_TENANT_LIST'