const PORT = '8000'
const HOST = 'http://localhost'
const ADDRESS = `${HOST}:${PORT}`

export const GET_TENANTS_LIST_URL = `${ADDRESS}/api/tenants`
export const GET_TENANTS_OVERVIEW_URL = `${ADDRESS}/api/tenant_overview`
export const GET_TENANTS_PLAN_OVERVIEW_URL = `${ADDRESS}/api/tenant_plan`
export const GET_SERVICE_OVERVIEW = `${ADDRESS}/api/service_overview`
export const GET_SERVICE_IO = `${ADDRESS}/api/data_series`
export const GET_LATENCY_SERIES = `${ADDRESS}/api/latency_series`
export const GET_USAGE_SERIES = `${ADDRESS}/api/service_usage_series`
export const GET_SERVICE_LIST_URL = `${ADDRESS}/api/service_list`
export const GET_TENANTS_LOGIN_ACTIVITY_URL =  `${ADDRESS}/api/login_activity`
export const GET_RESOURCE_HOST_OPTIONS =  `${ADDRESS}/api/host_options`
export const GET_RESOURCE_DISK_OPTIONS =  `${ADDRESS}/api/disk_options`
export const GET_RESOURCE_CPU_OPTIONS =  `${ADDRESS}/api/cpu_options`
export const GET_RESOURCE_OVERVIEW =  `${ADDRESS}/api/resource_overview`
export const GET_RESOURCE_CPU_USAGE_SERIES =  `${ADDRESS}/api/cpu_usage_series`
export const GET_RESOURCE_MEM_USAGE_SERIES =  `${ADDRESS}/api/mem_usage_series`
export const GET_RESOURCE_FS_USAGE_SERIES =  `${ADDRESS}/api/fs_usage_series`