export const SERVICE_GET_SERVICE_OVERVIEW = 'SERVICE_GET_SERVICE_OVERVIEW'
export const SERVICE_SET_SERVICE_OVERVIEW = 'SERVICE_SET_SERVICE_OVERVIEW'
export const SERVICE_GET_SERVICE_IO = 'SERVICE_GET_SERVICE_IO'
export const SERVICE_SET_SERVICE_IO = 'SERVICE_SET_SERVICE_IO'